import { AnalysisResults, ProcessAnalysis, Recommendation } from "@/types/analysis";

export const mockRecommendations: Recommendation[] = [
  {
    id: "rec-1",
    priority: "high",
    framework: "Josh Bersin",
    title: "Implement Skills-Based Talent Architecture",
    description: "Your current hiring process lacks skills taxonomy integration. Implement a dynamic skills framework that maps to business capabilities.",
    impact: "40% improvement in time-to-productivity for new hires",
    effort: "medium",
  },
  {
    id: "rec-2",
    priority: "high",
    framework: "Gartner",
    title: "Enable Continuous Performance Conversations",
    description: "Replace annual reviews with ongoing feedback mechanisms. Current 12-month review cycles are misaligned with modern performance management practices.",
    impact: "2.5x increase in employee engagement scores",
    effort: "low",
  },
  {
    id: "rec-3",
    priority: "medium",
    framework: "Dave Ulrich",
    title: "Strengthen HR Business Partner Capabilities",
    description: "Your HRBP function shows limited strategic advisory involvement. Invest in business acumen training and restructure reporting lines.",
    impact: "Elevate HR from administrative to strategic function",
    effort: "high",
  },
  {
    id: "rec-4",
    priority: "medium",
    framework: "Josh Bersin",
    title: "Deploy AI-Powered Talent Marketplace",
    description: "Enable internal mobility through an intelligent matching platform. Current internal transfer rate of 8% is below industry benchmark of 25%.",
    impact: "35% reduction in external hiring costs",
    effort: "medium",
  },
  {
    id: "rec-5",
    priority: "low",
    framework: "Gartner",
    title: "Modernize Learning Experience Platform",
    description: "Current LMS shows low engagement metrics. Migrate to a modern LXP with personalized learning paths and social learning features.",
    impact: "3x improvement in learning completion rates",
    effort: "high",
  },
];

export const mockProcesses: ProcessAnalysis[] = [
  {
    id: "proc-1",
    processName: "Hire Employee",
    status: "partial",
    overallScore: 72,
    frameworks: {
      bersin: {
        name: "Josh Bersin Academy",
        score: 68,
        maxScore: 100,
        status: "partial",
        description: "Skills-based hiring partially implemented",
        recommendations: ["Integrate skills taxonomy", "Add AI screening"],
      },
      gartner: {
        name: "Gartner HR Framework",
        score: 75,
        maxScore: 100,
        status: "partial",
        description: "Candidate experience needs enhancement",
        recommendations: ["Reduce time-to-offer", "Improve feedback loops"],
      },
      ulrich: {
        name: "Dave Ulrich Model",
        score: 73,
        maxScore: 100,
        status: "partial",
        description: "Strategic talent acquisition alignment improving",
        recommendations: ["Strengthen workforce planning integration"],
      },
    },
    logs: [
      { id: "log-1", timestamp: "2024-12-20T10:30:00Z", processType: "Hire", action: "Requisition Created", status: "Success", details: "Engineering Manager role" },
      { id: "log-2", timestamp: "2024-12-20T14:15:00Z", processType: "Hire", action: "Candidate Screened", status: "Success", details: "AI screening completed" },
    ],
    recommendations: mockRecommendations.slice(0, 2),
  },
  {
    id: "proc-2",
    processName: "Performance Review",
    status: "misaligned",
    overallScore: 45,
    frameworks: {
      bersin: {
        name: "Josh Bersin Academy",
        score: 42,
        maxScore: 100,
        status: "misaligned",
        description: "Annual review cycle outdated",
        recommendations: ["Move to continuous feedback", "Add OKR integration"],
      },
      gartner: {
        name: "Gartner HR Framework",
        score: 48,
        maxScore: 100,
        status: "misaligned",
        description: "Manager capabilities underdeveloped",
        recommendations: ["Coach manager training", "Implement calibration"],
      },
      ulrich: {
        name: "Dave Ulrich Model",
        score: 45,
        maxScore: 100,
        status: "misaligned",
        description: "Performance-business linkage weak",
        recommendations: ["Align to business outcomes", "Strategic HR BP involvement"],
      },
    },
    logs: [
      { id: "log-3", timestamp: "2024-12-15T09:00:00Z", processType: "Performance", action: "Review Initiated", status: "Success", details: "Q4 annual review" },
    ],
    recommendations: mockRecommendations.slice(1, 3),
  },
  {
    id: "proc-3",
    processName: "Learning & Development",
    status: "aligned",
    overallScore: 88,
    frameworks: {
      bersin: {
        name: "Josh Bersin Academy",
        score: 90,
        maxScore: 100,
        status: "aligned",
        description: "Strong learning culture established",
        recommendations: ["Expand skills-based learning paths"],
      },
      gartner: {
        name: "Gartner HR Framework",
        score: 85,
        maxScore: 100,
        status: "aligned",
        description: "Learning experience modern and engaging",
        recommendations: ["Add social learning features"],
      },
      ulrich: {
        name: "Dave Ulrich Model",
        score: 89,
        maxScore: 100,
        status: "aligned",
        description: "L&D supports business strategy",
        recommendations: ["Strengthen leadership development"],
      },
    },
    logs: [
      { id: "log-4", timestamp: "2024-12-18T11:00:00Z", processType: "Learning", action: "Course Completed", status: "Success", details: "Leadership fundamentals" },
    ],
    recommendations: mockRecommendations.slice(4),
  },
  {
    id: "proc-4",
    processName: "Compensation Management",
    status: "partial",
    overallScore: 65,
    frameworks: {
      bersin: {
        name: "Josh Bersin Academy",
        score: 60,
        maxScore: 100,
        status: "partial",
        description: "Pay equity analysis needs automation",
        recommendations: ["Implement AI-driven pay equity tools"],
      },
      gartner: {
        name: "Gartner HR Framework",
        score: 70,
        maxScore: 100,
        status: "partial",
        description: "Total rewards communication improving",
        recommendations: ["Enhance rewards visibility"],
      },
      ulrich: {
        name: "Dave Ulrich Model",
        score: 65,
        maxScore: 100,
        status: "partial",
        description: "Compensation strategy alignment moderate",
        recommendations: ["Link pay to strategic outcomes"],
      },
    },
    logs: [],
    recommendations: mockRecommendations.slice(2, 4),
  },
];

export const mockAnalysisResults: AnalysisResults = {
  overallScore: 67,
  totalProcesses: 4,
  alignedCount: 1,
  partialCount: 2,
  misalignedCount: 1,
  processes: mockProcesses,
  executiveSummary: "Your organization demonstrates moderate alignment with industry-leading HR practices. While Learning & Development shows strong maturity (88%), Performance Management requires urgent attention (45%). Key opportunities exist in implementing continuous feedback mechanisms, skills-based talent architecture, and strengthening HR business partner capabilities. Addressing the top 3 recommendations could improve overall HR effectiveness by 25-30%.",
  topRecommendations: mockRecommendations.slice(0, 3),
};
